# code_generator.py

import os
import re
import tempfile

class DriverCodeGenerator:
    """
    严格按照Profile脚本和用户参考风格，生成1:1对应的C驱动代码。
    """
    def __init__(self, profile):
        self.profile = profile
        self.ic_name = profile.get("ic_name", "ePaper_IC")
        self.profile_root = profile.get("__root_path__", ".")
        self.resolution = profile.get("resolution", {})
        self.width = self.resolution.get("width", 0)
        self.height = self.resolution.get("height", 0)
        self.buffer_size = (self.width * self.height) // 8

    def generate_code(self, parts_to_generate):
        code_blocks = []
        # (代码不变)
        if 'header' in parts_to_generate:
            code_blocks.append(self._generate_header())
        if 'lut' in parts_to_generate:
            code_blocks.append(self._generate_lut())
        if 'reset' in parts_to_generate:
            code_blocks.append(self._generate_reset())
        if 'init' in parts_to_generate:
            code_blocks.append(self._generate_init())
        if 'display' in parts_to_generate:
            code_blocks.append(self._generate_display_functions())
        if 'sleep' in parts_to_generate:
            code_blocks.append(self._generate_sleep())
        return "\n\n".join(filter(None, code_blocks))

    def _generate_header(self):
        # (代码不变)
        return f"""/******************************************************************************
* @file      epd_driver_{self.ic_name.lower()}.c
* @brief     Driver for {self.ic_name} E-Paper Display
* @author    Generated by E-Paper-Pro Suite
*
* @note
* This driver is a direct translation of the scripts in your profile.
* Please implement the low-level hardware functions (SPI, GPIO etc.).
******************************************************************************/
#include "stdint.h"
#include "stdio.h" // For printf

// Screen resolution
#define EPD_WIDTH    {self.width}
#define EPD_HEIGHT   {self.height}
#define EPD_BUFFER_SIZE  ({self.width} * {self.height} / 8)

// Low-level hardware function prototypes (Please implement these)
void SPI2_Write_Cmd(uint8_t command);
void SPI2_Write_Data(uint8_t data);
void HAL_Delay(uint32_t ms);
#define EPD_Reset_H // Example: HAL_GPIO_WritePin(RST_GPIO_Port, RST_Pin, GPIO_PIN_SET)
#define EPD_Reset_L // Example: HAL_GPIO_WritePin(RST_GPIO_Port, RST_Pin, GPIO_PIN_RESET)
#define EPD_BUSY_STATUS // Example: HAL_GPIO_ReadPin(BUSY_GPIO_Port, BUSY_Pin) == GPIO_PIN_SET

/**
 * @brief  Waits until the EPD is no longer busy.
 */
void ReadBusy(void)
{{
    printf("e-Paper busy\\r\\n");
    while (EPD_BUSY_STATUS == 0); // 0: busy, 1: idle (Please adjust this logic based on your hardware)
    printf("e-Paper busy release\\r\\n");
}}
"""

    # --- [核心修复] 用这个新版本替换旧的 _parse_script_strictly 函数 ---
    def _parse_script_strictly(self, script_path, display_func_type=None):
        """
        严格的脚本解析器，能正确处理行尾注释，并将'#'转换为'//'。
        同时兼容 WAIT 和 WAIT_BUSY 指令。
        """
        code_lines = []
        if not os.path.exists(script_path):
            return [f"    // ERROR: Script file not found: {os.path.basename(script_path)}"]

        placeholder_count = 0
        with open(script_path, 'r', encoding='utf-8') as f:
            for line in f:
                full_line = line.strip()
                if not full_line: continue
                if full_line.startswith('#'):
                    code_lines.append(f"    // {full_line.lstrip('#').strip()}")
                    continue
                if full_line.startswith('//'):
                    code_lines.append(f"    {full_line}")
                    continue
                
                command_part = full_line
                comment_part = ""
                if '//' in full_line:
                    parts = full_line.split('//', 1)
                    command_part = parts[0].strip()
                    comment_part = f"  // {parts[1].strip()}"
                elif '#' in full_line:
                    parts = full_line.split('#', 1)
                    command_part = parts[0].strip()
                    comment_part = f"  // {parts[1].strip()}"
                if not command_part: continue

                parts = command_part.split()
                # 兼容 "WAIT_BUSY:" 这样的写法，移除末尾的冒号
                command = parts[0].upper().rstrip(':')

                if command == "CMD":
                    code_lines.append(f"    SPI2_Write_Cmd({parts[1]});{comment_part}")
                elif command == "DATA":
                    for i, data_byte in enumerate(parts[1:]):
                        data_line = f"    SPI2_Write_Data({data_byte});"
                        if i == 0: code_lines.append(data_line + comment_part)
                        else: code_lines.append(data_line)
                elif command == "DELAY":
                    code_lines.append(f"    HAL_Delay({parts[1]});{comment_part}")
                elif command == "WAIT" or command == "WAIT_BUSY": # 兼容两种写法
                    code_lines.append(f"    ReadBusy();{comment_part}")
                elif command == "PIN":
                    pin, state = parts[1].upper(), parts[2].upper()
                    if pin == "RST":
                        pin_macro = "EPD_Reset_L" if state == "LOW" else "EPD_Reset_H"
                        code_lines.append(f"    {pin_macro};{comment_part}")
                elif command == "SEND_LUT_DATA_CHUNK":
                    start, end = parts[1], parts[2]
                    code_lines.append(f"    for(unsigned int count = {start}; count < {end}; count++) {{")
                    code_lines.append(f"        SPI2_Write_Data(lut[count]);")
                    code_lines.append(f"    }}{comment_part}")
                elif command == "SEND_IMAGE_DATA":
                    if display_func_type == 'BW':
                        code_lines.append(f"    for(unsigned int i = 0; i < EPD_BUFFER_SIZE; i++) {{")
                        code_lines.append(f"        SPI2_Write_Data(dat[i]);")
                        code_lines.append(f"    }}{comment_part}")
                    elif display_func_type == '4Gray':
                        placeholder_count += 1
                        buffer_name = "image_bw" if placeholder_count == 1 else "image_gray"
                        comment = f"// Frame {placeholder_count} ({buffer_name})"
                        code_lines.append(f"    {comment}")
                        code_lines.append(f"    for(unsigned int i = 0; i < EPD_BUFFER_SIZE; i++) {{")
                        code_lines.append(f"        SPI2_Write_Data({buffer_name}[i]);")
                        code_lines.append(f"    }}{comment_part}")

        return code_lines

    def _format_c_function(self, signature, comment, body_lines):
        # (代码不变)
        body = "\n".join(body_lines)
        return f"/**\n * @brief  {comment}\n */\n{signature}\n{{\n{body}\n}}"

    def _generate_reset(self):
        # (代码不变)
        body = [
            '    printf("EPD Reset\\r\\n");', '    HAL_Delay(10);', '    EPD_Reset_H;',
            '    HAL_Delay(10);', '    EPD_Reset_L;', '    HAL_Delay(10);',
            '    EPD_Reset_H;', '    printf("EPD Reset Done\\r\\n");'
        ]
        return self._format_c_function("void Hardware_Reset(void)", "Hardware reset for the E-Paper Display.", body)

    def _generate_init(self):
        # (代码不变)
        init_map = self.profile.get("initializations")
        init_script_path = ""
        init_name = "Default Init"
        if init_map and isinstance(init_map, dict):
            if "Default Init" in init_map:
                 init_name = "Default Init"; init_script_path = init_map["Default Init"]
            else:
                 init_name = next(iter(init_map)); init_script_path = init_map[init_name]
        elif "init_script" in self.profile:
            init_script_path = self.profile.get("init_script"); init_name = "Initialization"
        if not init_script_path:
            return "// ERROR: Could not find 'initializations' dictionary or 'init_script' string in profile."
        full_path = os.path.join(self.profile_root, init_script_path)
        body = self._parse_script_strictly(full_path)
        return self._format_c_function(f"void {self.ic_name}_Init(void)", f"Initialization sequence ({init_name}).", body)

    def _generate_lut(self):
        # (代码不变)
        lut_source_file = self.profile.get("lut_source_file")
        if not lut_source_file: return ""
        lut_file_path = os.path.join(self.profile_root, lut_source_file)
        if not os.path.exists(lut_file_path): return f"// LUT file not found: {lut_source_file}"
        with open(lut_file_path, 'r', encoding='utf-8') as f: lut_data_str = f.read()
        lut_data_str = re.sub(r'const\s+uint8_t\s+\w+\[', f'const uint8_t {self.ic_name}_Lut[] = //', lut_data_str, 1)
        update_script_path = os.path.join(self.profile_root, self.profile.get("scripts", {}).get("update_lut", ""))
        body = self._parse_script_strictly(update_script_path)
        update_func_str = self._format_c_function(
            f"void Lut_Load(const uint8_t *lut)", "Load the Look-Up Table (Waveform) data into the EPD controller.", body
        )
        return f"// Look-Up Table (Waveform) data\n{lut_data_str}\n\n{update_func_str}"

    def _generate_display_functions(self):
        # (代码不变)
        all_funcs = []
        gc_script_path = os.path.join(self.profile_root, self.profile.get("scripts", {}).get("display_full_gc", ""))
        if os.path.exists(gc_script_path):
            with open(gc_script_path, 'r', encoding='utf-8') as f: script_content = f.read()
            parts = script_content.split("SEND_IMAGE_DATA")
            if len(parts) > 1 and parts[1].strip():
                with tempfile.NamedTemporaryFile(mode='w', delete=False, encoding='utf-8') as tmp:
                    tmp.write(parts[1])
                    update_body = self._parse_script_strictly(tmp.name)
                os.remove(tmp.name)
                all_funcs.append(self._format_c_function("void Display_Update(void)", "Update the display with data from RAM.", update_body))
            dis_pic_body = self._parse_script_strictly(gc_script_path, display_func_type="BW")
            all_funcs.append(self._format_c_function("void Dis_Pic(const uint8_t *dat)", "Display a full picture.", dis_pic_body))
        gray_script_path = os.path.join(self.profile_root, self.profile.get("scripts", {}).get("display_4gray", ""))
        if os.path.exists(gray_script_path):
            body = self._parse_script_strictly(gray_script_path, display_func_type="4Gray")
            all_funcs.append(self._format_c_function("void Dis_Pic_4Gray(const uint8_t *image_bw, const uint8_t *image_gray)", "Display a 4-grayscale picture.", body))
        return "\n\n".join(all_funcs)
        
    def _generate_sleep(self):
        # (代码不变)
        script_path = os.path.join(self.profile_root, self.profile.get("scripts", {}).get("sleep", ""))
        if not os.path.exists(script_path): return ""
        body = self._parse_script_strictly(script_path)
        return self._format_c_function("void EPD_Sleep(void)", "Puts the display into deep sleep mode.", body)